
# FILES
defaults: # (these specify which config FILES to use)
  ############## TRAIN ###################################
  #- data: yelp_reviews_2L
  #- data: vader_nyt_2L
  - data: template            # use data=<dataset>_<method> at runtime, e.g. data=mpqa_biois
  #- model: llama3.1
  - model: roberta
  #- model: lr
  - paths: default
  - _self_

config: 
  random_seed: 42
  
#model:
  #text_representation: bert
  #text_representation: llama3.1
  #load_representation: True


